# This Workflow announces a release in Eclipse Mattermost to https://mattermost.eclipse.org/eclipse/channels/eclipse-che-releases
name: Release - Send mattermost notification
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be announced. Should be in format 7.y.z'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create message
      run: |
        milestone=${{ github.event.inputs.version }}
        milestone=${milestone%.*}; echo "milestone: ${milestone}"
        echo "{\"text\":\":che-logo: Che ${{ github.event.inputs.version }} has been released.\n\nPlease resolve or move unresolved issues assigned to this milestone: https://github.com/eclipse/che/milestones/${milestone}\"}" > mattermost.json
    - name: Send message
      uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-releases
        MATTERMOST_USERNAME: che-bot
